spring:
  datasource:
    url: jdbc:mariadb://172.17.0.2:3306/board
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mariadb
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
